[build]
output = "./src/token.ts"
prefix = "empty"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

# ─── 容器 ────────────────────────────────────────────────────────────────────

container.padding    = "$ref(space.dialog-padding)"
container.min-height = "200px"


# ─── 图像 ────────────────────────────────────────────────────────────────────

image.width        = "var(--empty-image-size, 80px)"
image.color        = "$ref(color.fill.default)"
image.margin-bottom = "$ref(space.stack-gap)"


# ─── 标题 ────────────────────────────────────────────────────────────────────

title.color         = "$ref(color.text.secondary)"
title.font-size     = "$ref(font.size.subhead)"
title.font-weight   = "$ref(typography.label.font-weight)"
title.margin-bottom = "$ref(space.component-gap)"


# ─── 描述 ────────────────────────────────────────────────────────────────────

description.color         = "$ref(color.text.tertiary)"
description.font-size     = "$ref(typography.caption.font-size)"
description.margin-bottom = "$ref(space.stack-gap)"
