approvedGitRepositories:
  - "**"

enableScripts: false

enableGlobalCache: false

nodeLinker: pnp

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NODE_AUTH_TOKEN-}"

packageExtensions:
  "@crab-dev/rc-dropdown-container@0.0.3": &crabRuntime
    dependencies:
      "@crab-dev/css": "0.1.45"
      "@types/react": "^19.3.0"
      "lucide-react": "^1.23.0"
      "react": "19.3.0"
      "react-dom": "19.3.0"
  "@crab-dev/rc-hooks@0.0.2": *crabRuntime
  "@crab-dev/rc-select@0.0.3": *crabRuntime
  "@crab-dev/rc-spin@0.0.2": *crabRuntime
  "@crab-dev/rc-token-semantic@0.0.2": *crabRuntime
  "@crab-dev/rc-tooltip@0.0.2": *crabRuntime
  "elkjs@0.12.0":
    dependencies:
      web-worker: "1.4.1"
  "lucide-react@*":
    dependencies:
      "@types/react": "^19.3.0"
