approvedGitRepositories:
  - "**"

enableScripts: false

nodeLinker: pnp

npmMinimalAgeGate: 0

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  //registry.npmjs.org:
    npmAuthToken: "${NODE_AUTH_TOKEN-}"

packageExtensions:
  jest-config@*:
    dependencies:
      ts-node: "*"
