[build]
output = "./src/token.ts"
prefix = "notification"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

background.color = "$ref(color.background.elevated)"
text.color = "$ref(color.text.primary)"
padding = "$ref(space.card-padding) $ref(space.dialog-padding)"
border.radius = "$ref(radius.lg)"

title.margin.bottom = "$ref(space.component-gap)"
title.font.size = "$ref(font.size.subhead)"
title.line.height = "1.5"

content.font.size = "$ref(font.size.body)"

progress.start.color = "$ref(color.feedback.success)"
progress.end.color = "$ref(color.feedback.success)"
progress.height = "3px"

close.opacity = "$ref(opacity.tertiary)"