[build]
output = "./src/token.ts"
prefix = "notification"

[token]

background.color = "white"
text.color = "rgba(0,0,0,0.88)"
padding = "20px 24px"
border.radius = "8px"

title.margin.bottom = "10px"
title.font.size = "16px"
title.line.height = "1.5"

content.font.size = "14px"

progress.start.color = "#22c55e"
progress.end.color = "#16a34a"
progress.height = "3px"

close.opacity = "0.7"