[build]
output = "./src/token.ts"
prefix = "dropdown-container"
imports = ["@crab-dev/rc-token-semantic"]

[token]
root.box-shadow = "$ref(shadow.float)"
root.border-radius = "$ref(shape.extra-small)"
root.background-color = "$ref(color.surface.container)"
root.border-color = "transparent"
root.z-index = "$ref(z-index.float)"

motion.interaction.transition = "$ref(motion.interaction)"
motion.offset.translate = "calc($ref(space.component-gap) * -1)"

interaction.touch.min-width = "$ref(size.touch-target)"
interaction.touch.min-height = "$ref(size.touch-target)"
interaction.outline-color-focus = "$ref(color.focus.ring)"
interaction.outline-width-focus = "2px"
interaction.outline-offset-focus = "2px"
root.max-width = "calc(100vw - $ref(space.section-gap))"

motion.spatial.transition = "$ref(motion.spatial.fast)"
