[build]
output = "./src/token.ts"
prefix = "color-picker"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

panel.padding = "$ref(space.section-gap)"
panel.gap = "$ref(space.section-gap)"

panel.preview.height = "5rem"
panel.preview.width = "100%"
panel.preview.border.radius = "$ref(radius.lg)"
panel.preview.margin.top = "$ref(space.section-gap)"

panel.slider.container.gap = "$ref(space.section-gap)"