[build]
output = "./src/token.ts"
prefix = "tooltip"
imports = ["@crab-dev/rc-token-semantic"]

[token]
root.background-color = "$ref(color.background.inverse)"
root.color = "$ref(color.text.inverse)"
root.padding-inline = "$ref(space.component-gap)"
root.padding-block = "$ref(space.inline-gap)"
root.font-size = "$ref(typography.body.small.font-size)"
root.line-height = "$ref(typography.body.small.line-height)"
root.border-radius = "$ref(shape.extra-small)"
root.max-width = "250px"
root.z-index = "$ref(z-index.elevated)"

motion.interaction.transition = "$ref(motion.interaction)"

interaction.touch.min-width = "$ref(size.touch-target)"
interaction.touch.min-height = "$ref(size.touch-target)"
interaction.outline-color-focus = "$ref(color.focus.ring)"
interaction.outline-width-focus = "2px"
interaction.outline-offset-focus = "2px"
root.box-shadow = "none"
root.outline-width = "1px"
