[build]
output = "./src/token.ts"
prefix = "dialog"

[token.color]
overlay-background-color = "rgba(0,0,0,0.45)"

[token.dimension]
padding = "20px 24px"
border-radius = "8px"
heading-margin-bottom = "15px"
footer-margin-top = "12px"
footer-button-spacing = "8px"

[token.typography]
heading-font-weight = "600"
heading-font-size = "16px"
heading-line-height = "1.5"

[token.motion]

[token.elevation]
box-shadow = "0 6px 16px 0 rgba(0, 0, 0, 0.08), 0 3px 6px -4px rgba(0, 0, 0, 0.12), 0 9px 28px 8px rgba(0, 0, 0, 0.05)"

[token.border]

[token.opacity]