[build]
output = "./src/token.ts"
prefix = "button"

[token.color]
primary = "oklch(1 0 0)"
primary-background = "oklch(0.2855 0.0113 271)"
primary-background-hover = "oklch(0.2442 0.0077 274.63)"
primary-background-active = "oklch(0.2855 0.0113 271)"

link = "oklch(0.3608 0.0113 271)"
link-hover = "oklch(0.3608 0.0113 271)"
link-active = "oklch(0.3608 0.0113 271)"
link-background = "transparent"
link-background-disabled = "transparent"

dashed = "oklch(0.2855 0.0113 271)"
dashed-hover = "oklch(0.2855 0.0113 271)"
dashed-active = "oklch(0.2855 0.0113 271)"
dashed-background = "oklch(1 0 0)"

text-background-hover = "rgba(0,0,0,0.04)"
text-background-active = "rgba(0,0,0,0.15)"

subtle = "oklch(0 0 0 / 88%)"
subtle-hover = "oklch(0 0 0 / 88%)"
subtle-active = "oklch(0 0 0 / 88%)"
subtle-background = "oklch(1 0 0)"

[token.dimension]
large-gap = "10px"
large-height = "40px"
large-padding = "0 15px"
large-border-radius = "10px"

middle-gap = "8px"
middle-height = "32px"
middle-padding = "0 15px"
middle-border-radius = "8px"

small-gap = "6px"
small-height = "24px"
small-padding = "0 7px"
small-border-radius = "6px"

[token.typography]
large-font-size = "16px"
middle-font-size = "14px"
small-font-size = "14px"
font-family = "inherit"

link-text-underline-offset = "4px"
link-text-decoration = "underline solid red 2px"

[token.motion]
transition = "transform 90ms ease-out, box-shadow 90ms ease-out, background-color 90ms ease-out"

[token.elevation]
primary-box-shadow = "oklch(0.6518 0.1916 251.64 / 10%) 0px 2px 0px 0px"
dashed-box-shadow = "oklch(0 0 0 / 2%) 0px 2px 0px 0px"
subtle-box-shadow = "0 2px 0 oklch(0 0 0 / 2%)"

[token.border]
subtle-width = "1px"
subtle-style = "solid"
subtle-color = "oklch(0.8853 0 0)"
subtle-color-hover = "oklch(0.8853 0 0)"
subtle-color-active = "oklch(0.8853 0 0)"

dashed-width = "1px"
dashed-style = "dashed"
dashed-color = "oklch(0.2855 0.0113 271)"
dashed-color-hover = "oklch(0.2855 0.0113 271)"
dashed-color-active = "oklch(0.2855 0.0113 271)"

[token.opacity]
loading = "0.65"