[build]
output = "./src/token.ts"
prefix = "slider"

[token]

rail.interact.height = "12px"
rail.thickness = "4px"
rail.inactive.fill = "#e5e7eb"
rail.active.fill = "#3b82f6"

thumb.radius = "8px"
thumb.fill = "#ffffff"
thumb.stroke.color = "#3b82f6"
thumb.stroke.width = "2.5px"
thumb.halo.scale.factor = 1.8
thumb.halo.fill = "#3b82f6"