import { defineTokens } from "@crab-dev/css";
import palette from "@crab-dev/rc-token-global";

export const themeSelectors = {
    light: ':root, [data-theme="light"]',
    dark: '[data-theme="dark"]',
    forcedColors: "@media (forced-colors: active)",
} as const;

export const themeColorContract = defineTokens({
    light: {
        brand: {
            primary: palette.zinc["900"],
            hover: palette.zinc["800"],
            active: palette.zinc["950"],
            subtle: palette.zinc["600"],
        },
        background: {
            surface: palette.white,
            elevated: palette.white,
            sunken: palette.zinc["50"],
            inverse: palette.zinc["950"],
            overlay: `color-mix(in oklch, ${palette.black} 45%, transparent)`,
            disabled: palette.zinc["100"],
            hoverSubtle: palette.zinc["100"],
            activeSubtle: palette.zinc["200"],
            selected: palette.blue["50"],
        },
        text: {
            primary: palette.zinc["950"],
            secondary: palette.zinc["700"],
            tertiary: palette.zinc["600"],
            onBrand: palette.zinc["50"],
            inverse: palette.zinc["50"],
            disabled: palette.zinc["500"],
            link: palette.zinc["900"],
            linkHover: palette.zinc["700"],
        },
        border: {
            subtle: palette.zinc["200"],
            default: palette.zinc["500"],
            hover: palette.zinc["600"],
            strong: palette.zinc["700"],
            focus: palette.blue["600"],
            error: palette.red["600"],
        },
        focusRing: `var(--token-semantic-color-border-focus, ${palette.blue["600"]})`,
        selection: {
            background: palette.blue["50"],
            border: palette.blue["700"],
            foreground: palette.zinc["950"],
        },
        highlight: {
            background: palette.amber["100"],
            backgroundActive: palette.amber["300"],
            foreground: palette.zinc["950"],
        },
        feedback: {
            error: {
                text: `var(--token-semantic-color-feedback-error, ${palette.red["800"]})`,
                icon: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                border: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                background: palette.red["50"],
                backgroundHover: palette.red["100"],
                solid: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                solidHover: palette.red["700"],
                solidActive: palette.red["800"],
                onSolid: palette.white,
            },
            success: {
                text: `var(--token-semantic-color-feedback-success, ${palette.green["800"]})`,
                icon: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                border: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                background: palette.green["50"],
                backgroundHover: palette.green["100"],
                solid: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                solidHover: palette.green["800"],
                solidActive: palette.green["900"],
                onSolid: palette.white,
            },
            warning: {
                text: `var(--token-semantic-color-feedback-warning, ${palette.amber["900"]})`,
                icon: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                border: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                background: palette.amber["50"],
                backgroundHover: palette.amber["100"],
                solid: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                solidHover: palette.amber["800"],
                solidActive: palette.amber["900"],
                onSolid: palette.white,
            },
            info: {
                text: `var(--token-semantic-color-feedback-info, ${palette.blue["800"]})`,
                icon: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                border: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                background: palette.blue["50"],
                backgroundHover: palette.blue["100"],
                solid: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                solidHover: palette.blue["700"],
                solidActive: palette.blue["800"],
                onSolid: palette.white,
            },
        },
        fill: {
            subtle: palette.zinc["100"],
            default: palette.zinc["300"],
            strong: palette.zinc["700"],
            translucent: `color-mix(in oklch, ${palette.black} 8%, transparent)`,
            inactive: palette.zinc["300"],
            active: palette.zinc["900"],
        },
        focusShadow: `0 0 0 3px var(--token-semantic-color-focus-ring, var(--token-semantic-color-border-focus, ${palette.blue["600"]}))`,
    },
    dark: {
        brand: {
            primary: palette.zinc["50"],
            hover: palette.zinc["200"],
            active: palette.white,
            subtle: palette.zinc["300"],
        },
        background: {
            surface: palette.zinc["950"],
            elevated: palette.zinc["900"],
            sunken: palette.black,
            inverse: palette.white,
            overlay: `color-mix(in oklch, ${palette.black} 72%, transparent)`,
            disabled: palette.zinc["800"],
            hoverSubtle: palette.zinc["800"],
            activeSubtle: palette.zinc["700"],
            selected: palette.blue["950"],
        },
        text: {
            primary: palette.zinc["50"],
            secondary: palette.zinc["300"],
            tertiary: palette.zinc["400"],
            onBrand: palette.zinc["950"],
            inverse: palette.zinc["950"],
            disabled: palette.zinc["500"],
            link: palette.zinc["50"],
            linkHover: palette.zinc["300"],
        },
        border: {
            subtle: palette.zinc["800"],
            default: palette.zinc["600"],
            hover: palette.zinc["500"],
            strong: palette.zinc["400"],
            focus: palette.blue["400"],
            error: palette.red["400"],
        },
        focusRing: `var(--token-semantic-color-border-focus, ${palette.blue["400"]})`,
        selection: {
            background: palette.blue["950"],
            border: palette.blue["400"],
            foreground: palette.zinc["50"],
        },
        highlight: {
            background: palette.amber["950"],
            backgroundActive: palette.amber["800"],
            foreground: palette.zinc["50"],
        },
        feedback: {
            error: {
                text: `var(--token-semantic-color-feedback-error, ${palette.red["300"]})`,
                icon: `var(--token-semantic-color-feedback-error, ${palette.red["400"]})`,
                border: `var(--token-semantic-color-feedback-error, ${palette.red["400"]})`,
                background: `color-mix(in oklch, ${palette.red["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklch, ${palette.red["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                solidHover: palette.red["700"],
                solidActive: palette.red["800"],
                onSolid: palette.white,
            },
            success: {
                text: `var(--token-semantic-color-feedback-success, ${palette.green["300"]})`,
                icon: `var(--token-semantic-color-feedback-success, ${palette.green["500"]})`,
                border: `var(--token-semantic-color-feedback-success, ${palette.green["500"]})`,
                background: `color-mix(in oklch, ${palette.green["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklch, ${palette.green["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                solidHover: palette.green["800"],
                solidActive: palette.green["900"],
                onSolid: palette.white,
            },
            warning: {
                text: `var(--token-semantic-color-feedback-warning, ${palette.amber["300"]})`,
                icon: `var(--token-semantic-color-feedback-warning, ${palette.amber["500"]})`,
                border: `var(--token-semantic-color-feedback-warning, ${palette.amber["500"]})`,
                background: `color-mix(in oklch, ${palette.amber["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklch, ${palette.amber["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                solidHover: palette.amber["800"],
                solidActive: palette.amber["900"],
                onSolid: palette.white,
            },
            info: {
                text: `var(--token-semantic-color-feedback-info, ${palette.blue["300"]})`,
                icon: `var(--token-semantic-color-feedback-info, ${palette.blue["500"]})`,
                border: `var(--token-semantic-color-feedback-info, ${palette.blue["500"]})`,
                background: `color-mix(in oklch, ${palette.blue["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklch, ${palette.blue["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                solidHover: palette.blue["700"],
                solidActive: palette.blue["800"],
                onSolid: palette.white,
            },
        },
        fill: {
            subtle: palette.zinc["800"],
            default: palette.zinc["600"],
            strong: palette.zinc["300"],
            translucent: `color-mix(in oklch, ${palette.white} 12%, transparent)`,
            inactive: palette.zinc["700"],
            active: palette.zinc["50"],
        },
        focusShadow: `0 0 0 3px var(--token-semantic-color-focus-ring, var(--token-semantic-color-border-focus, ${palette.blue["400"]}))`,
    },
});
