[build]
output = "./src/token.ts"
prefix = "line-edit"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

transition = "$ref(motion.fade)"
border.radius = "$ref(radius.md)"
border.width = "1px"
border.style = "solid"
border.color = "$ref(color.border.default)"
border.color-focus = "$ref(color.border.focus)"
box-shadow.default = "$ref(shadow.float)"
box-shadow.focus-within = "$ref(shadow.float)"
background.color = "transparent"
placeholder.color = "$ref(color.text.secondary)"
icon.color = "$ref(color.text.secondary)"
icon.margin-right = "$ref(space.component-gap)"

size.large.height = "40px"
size.large.padding = "$ref(space.inline-gap) $ref(space.control-padding-x)"
size.large.font.size = "$ref(font.size.subhead)"
size.large.line-height = "1.5rem"

size.middle.height = "32px"
size.middle.padding = "$ref(space.inline-gap) $ref(space.control-padding-x)"
size.middle.font.size = "$ref(font.size.body)"
size.middle.line-height = "1.25rem"

size.small.height = "24px"
size.small.padding = "$ref(space.inline-gap) $ref(space.control-padding-x)"
size.small.font.size = "$ref(font.size.body)"
size.small.line-height = "1.25rem"
