[build]
output = "./src/token.ts"
prefix = "message"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

# ─── 通用 ────────────────────────────────────────────────────────────────────
root.padding = "$ref(space.section-gap)"
root.border-radius = "$ref(shape.extra-small)"
root.font-size = "$ref(typography.body.medium.font-size)"
root.line-height = "$ref(typography.body.medium.line-height)"
root.background-color = "$ref(color.background.inverse)"
root.box-shadow = "$ref(shadow.overlay)"

# ─── 图标 ────────────────────────────────────────────────────────────────────
icon.width = "18px"
icon.margin-right = "$ref(space.component-gap)"

# ─── 类型颜色 ────────────────────────────────────────────────────────────────
success.icon.color = "$ref(color.text.inverse)"
warning.icon.color = "$ref(color.text.inverse)"
icon.color-error = "$ref(color.text.inverse)"
info.icon.color = "$ref(color.text.inverse)"

# ─── 文本 ────────────────────────────────────────────────────────────────────
text.color = "$ref(color.text.inverse)"

# ─── 进度条 ──────────────────────────────────────────────────────────────────
progress.start.color = "$ref(color.brand.primary)"
progress.end.color = "$ref(color.brand.primary-hover)"
progress.height = "3px"
progress.animation-duration = "0ms"
progress.animation-delay = "0ms"

motion.interaction.transition = "$ref(motion.interaction)"
stack.translate = "$ref(space.group-gap)"

motion.spatial.transition = "$ref(motion.spatial.fast)"
