[build]
output = "./src/token.ts"
prefix = "masonry"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

# ─── 通用 ────────────────────────────────────────────────────────────────────

root.transition = "var(--masonry-transition, transform $ref(motion.spatial.fast), opacity $ref(motion.interaction))"

# ─── 间距 ────────────────────────────────────────────────────────────────────

root.gap = "var(--masonry-gutter, $ref(space.component-gap))"
