[package]
name = "crab-core-websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
actix-ws = { workspace =  true }
futures-util = { workspace = true }
log = { workspace =  true }
anyhow = { workspace = true }
actix = { workspace = true}
actix-web-actors = { workspace = true}
