[build]
output = "./src/token.ts"
prefix = "tree"
imports = [
    "@crab-dev/rc-token-semantic"
]

[token]

indent.size = "$ref(space.dialog-padding)"
border.radius = "$ref(radius.sm)"

node.draggable.border.width = "1px"
node.draggable.border.style = "solid"
node.draggable.border.color = "$ref(color.border.focus)"

node.icon.hover.background.color = "$ref(color.background.hover-subtle)"
node.icon.loading.color = "$ref(color.brand.primary)"

node.hover.background.color = "$ref(color.background.hover-subtle)"
node.select.background.color = "$ref(color.background.active-subtle)"
