// Auto-generated by .crustify.ts. Do not edit.
export interface ToolManifestItem {
    slug: string;
    pkg: string;
    version: string;
    title: string;
    role: string;
    stage: string;
    summary: string;
    output: string;
    description: string;
    readme: string;
}

const toolboxManifest: ToolManifestItem[] = [
    {
        slug: "crustify",
        pkg: "@crab-dev/crustify",
        version: "0.0.19",
        title: "Crustify 开发构建器",
        role: "Webpack 5",
        stage: "开发",
        summary: "起本地开发服务器。React Compiler、Linaria、SWC 与 MDX 开箱即用，存盘即热更新。",
        output: "开发服务器与 HMR",
        description: "用来构建 React 开发的构建器, 预设了 babel 和 linaria 等一些配置",
        readme: `<div align="center">
	<h1>@crab-dev/crustify</h1>
	<p>
		基于 Webpack 5 的零配置 React 19 构建工具，<br/>
		集成 React Compiler、Linaria、SWC、MDX 和组件自动扫描，开箱即用。
	</p>
</div>

## 特性

- **零配置启动** — 内置完整的 Webpack 5 + Babel 配置，支持 TypeScript、React 19、CSS-in-JS
- **React Compiler** — 通过 \`babel-plugin-react-compiler\` 自动优化 React 组件
- **Linaria / wyw-in-js** — 零运行时 CSS-in-JS，构建期提取为静态 CSS
- **SWC** — 用于 \`bootstrap.tsx\` 的运行时 TSX 转换和 React SSR HTML 生成
- **MDX** — 原生支持 \`.mdx\` / \`.md\` 文件，集成 \`remark-gfm\` 和 \`remark-frontmatter\`
- **LightningCSS** — 现代 CSS 处理和压缩
- **组件自动扫描** — 自动发现指定目录下的组件，生成懒加载模块并提取 TOML frontmatter
- **多线程编译** — 通过 \`thread-loader\` 加速 Babel 和 wyw-in-js 处理
- **插件系统** — \`Modification\` 接口支持自定义入口、Webpack 配置和 HTML 模板

## 安装

\`\`\`bash
yarn add -D @crab-dev/crustify
\`\`\`

## CLI 命令

\`\`\`bash
crustify run-task app:dev     # 启动开发服务器（webpack-dev-server + HMR）
crustify run-task app:build   # 生产构建（输出到 dist/）
\`\`\`

## 项目结构

\`\`\`
src/
├── entry.tsx              # 应用入口文件
└── bootstrap.tsx          # HTML 外壳（通过 React SSR 渲染为 index.html）
.crustify.ts               # 配置文件
.tmp/                      # 自动生成（已 gitignore）
├── entry.tsx              # 生成的入口 → import("@/entry.tsx")
└── autoscan/
    └── tsconfig.json      # 自动扫描路径别名（IDE 支持）
dist/                      # 生产构建输出
\`\`\`

> \`.tmp/\`、\`.cache/\`、\`dist/\` 无需提交到代码仓库。

## 配置

在项目根目录创建 \`.crustify.ts\`（也支持 \`.mts\`、\`.js\`、\`.mjs\` 等，通过 \`unconfig\` 加载）：

\`\`\`ts
import { defineConfig } from "@crab-dev/crustify";

export default defineConfig({
    rootDir: process.cwd(),          // 项目根目录（默认 cwd）
    componentScan: [],               // 组件自动扫描规则
    mods: [],                        // 插件链
    devServer: {
        server: "http",              // "http" | "https"
        proxy: [],                   // 代理规则
    },
});
\`\`\`

## 路径别名

| 别名 | 解析到 |
|------|--------|
| \`@/\` | \`src/\` |
| \`@@/\` | 项目根目录 |
| \`@@@/{namespace}\` | 自动扫描生成的模块 |

## 组件自动扫描

配置 \`componentScan\` 后，Crustify 会在编译前自动扫描目录，生成懒加载模块：

\`\`\`ts
import { defineConfig } from "@crab-dev/crustify";
import { join } from "path";

export default defineConfig({
    componentScan: [{
        namespaces: "pages",                          // 通过 import pages from "@@@/pages" 访问
        cwd: join(process.cwd(), "src", "pages"),     // 扫描目录
        generateSourceCharacter: false,               // 是否在输出中包含源码
        include: undefined,                           // 文件包含正则
        exclude: undefined,                           // 文件排除正则
    }],
});
\`\`\`

生成的模块（位于 \`.tmp/\`）结构如下：

\`\`\`ts
const ___src_pages_index_page_tsx = import("@@/src/pages/index.page.tsx");

const components = [
    {
        name: "___src_pages_index_page_tsx",
        component: ___src_pages_index_page_tsx,
        path: "/src/pages/index.page.tsx",
        frontmatter: { "index": true },
        source: null,
    },
];

export default components;
\`\`\`

**Frontmatter 提取：** \`.tsx\` / \`.ts\` 文件中的首个块注释会被解析为 TOML；\`.mdx\` / \`.md\` 文件使用标准 TOML frontmatter。

> 如果 \`@@@/pages\` 缺少类型提示，将 \`.tmp/autoscan/tsconfig.json\` 添加到 \`tsconfig.json\` 的 \`extends\` 字段中。

## 插件系统（Modification）

通过实现 \`Modification\` 接口扩展构建流程：

\`\`\`ts
import type { Modification } from "@crab-dev/crustify";

const myMod: Modification = {
    // 修改 crustify 配置（最先执行）
    modifyConfig(config) { return config; },

    // 修改生成的入口文件内容
    modifyEntry(entry) { return entry; },

    // 修改 Webpack 配置
    modifyWebpack(configuration) { return configuration; },

    // 修改 bootstrap.tsx 查找路径
    modifyBootstrapPath(path) { return path; },
};
\`\`\`

在配置中注册：

\`\`\`ts
export default defineConfig({
    mods: [myMod],
});
\`\`\`

## HTML 生成

Crustify 通过 React SSR 生成 \`index.html\`：

1. 使用 SWC 将 \`src/bootstrap.tsx\` 转换为 JS
2. 通过 \`react-dom/server\` 的 \`renderToString()\` 渲染为 HTML
3. 自动注入编译产物的 \`<script defer>\` 和 \`<link>\` 标签
4. 开发模式下监听 \`bootstrap.tsx\` 变更，支持 HMR

## 内置 Babel 配置

| 预设 / 插件 | 作用 |
|-------------|------|
| \`@babel/preset-env\` | 环境适配（排除 \`plugin-transform-template-literals\` 以兼容 wyw-in-js） |
| \`@babel/preset-typescript\` | TypeScript 转译 |
| \`@babel/preset-react\` | React JSX（automatic runtime） |
| \`babel-plugin-react-compiler\` | React 19 Compiler（target: '19'） |
| \`@crab-dev/babel-plugin-auto-import-style\` | 自动注入组件样式导入 |`,
    },
    {
        slug: "lignify",
        pkg: "@crab-dev/lignify",
        version: "0.0.3",
        title: "Lignify 文档环境",
        role: "零配置",
        stage: "文档",
        summary: "零配置的文档与预览环境。自动扫描示例与 MDX，边写组件边调主题令牌。",
        output: "文档站与在线预览",
        description: "使用此快速开发 React 组件库，可用来调试和生成 CSS 变量主题。",
        readme: `<div align="center">
	<h1>@crab-dev/lignify</h1>
	<p>
		用于构建组件文档， 以及在线调试组件库的开发工具<br/>
		无需任何配置， 快速开始组件的开发，专注于组件的 <b>性能</b> 与 <b>可维护性</b>。
	</p>
</div>


## ✨ 特性

- ⚡ **零配置启动**：快速开始组件开发和提示
- 🧩 **支持主题调整**：开发时候, 默认支持 \`token.toml\` 主题样式变化的调整
- 🎨 **CSS-in-JS 支持**：原生支持 \`Linaria\` 和 \`@wyw-in-js\`，构建期提取样式，无运行时开销

## 📦 安装

\`\`\`bash
npm install @crab-dev/lignify --save-dev

yarn add -D @crab-dev/lignify

pnpm add -D @crab-dev/lignify
\`\`\`


## 🚀 快速开始

### 项目结构

大部分场景下，文件结构遵循约定生成。推荐的项目目录结构如下：

\`\`\`
├─ .cache              # 缓存目录，CSS 加载问题时可尝试删除
├─ .tmp                # 临时文件目录，可安全删除
├─ docs
├─ src                 # 源码目录
├─ token.toml          # 主题文件可选
├─ package.json        # 项目配置
├─ tsconfig.json       # TypeScript 配置
\`\`\`

## 🧩 自动生成侧边栏

侧边栏的数据根据 \`docs\` 目录中的 \`markdown\` 的头部文件进行生成

\`\`\`md
+++
name = "你好"
+++

这是一个 button 按钮的测试文档说明
\`\`\`


### 属性

| 属性名称       | 类型           | 描述
|-----------    |-------         |-----------
|id             | \`string\`       | 唯一 id，如果设置了，就使用这个 \`id\`, 不设置会默认生成一个 id
|title          | \`string\`       | 标题信息
|`,
    },
    {
        slug: "packify",
        pkg: "@crab-dev/packify",
        version: "0.0.4",
        title: "Packify 库打包器",
        role: "Rollup 4",
        stage: "构建",
        summary: "把组件打成库。一次构建同时产出四种格式，并生成设计令牌与 API 文档。",
        output: "esm / cjs / declarations / css",
        description: "用来构建依赖库的打包工具, 预设了 babel 和 linaria 等一些配置",
        readme: `<div align="center">
	<h1>@crab-dev/packify</h1>
	<p>
		基于 Rollup 4 的零配置库打包器，<br/>
		一条命令产出 ESM / CJS / 类型声明 / 静态 CSS，并负责设计令牌与 API 文档的生成。
	</p>
</div>

## 特性

- **零配置** — 入口固定为 \`src/index.ts\`，无需配置文件，约定优于配置
- **四种产物** — 一次构建同时输出 \`esm/\`、\`cjs/\`、\`declarations/\`、\`css/\`
- **Linaria / wyw-in-js** — 零运行时 CSS-in-JS，构建期把样式提取为静态 \`css/index.css\`
- **类名包名前缀** — 生成的类名以包名为前缀，根除不同组件包之间的类名哈希碰撞
- **React Compiler** — 内置 \`babel-plugin-react-compiler\`（\`target: '19'\`）
- **依赖全部外置** — 所有 npm 包保持 external，不打进产物，交由消费方的打包器处理
- **设计令牌生成** — 从 \`token.toml\` 生成 \`src/token.ts\`，支持 \`$ref()\` 跨层引用
- **API 文档生成** — 经 react-docgen 生成 \`public/docgen.json\`

## 安装

\`\`\`bash
yarn add -D @crab-dev/packify
\`\`\`

## CLI 命令

\`\`\`bash
packify build                # 构建库 → esm/ cjs/ declarations/ css/
packify test                 # 以 ESM 模式运行 Jest（透传参数与退出码）
packify generate:css-token   # token.toml → src/token.ts
packify generate:docgen      # react-docgen → public/docgen.json
\`\`\`

## 构建产物

\`packify build\` 先清空四个产物目录，再从 \`src/index.ts\` 出发构建：

\`\`\`
esm/index.mjs            # ES Module（terser 压缩）
cjs/index.cjs            # CommonJS（named exports，terser 压缩）
declarations/index.d.ts  # 类型声明（rollup-plugin-dts 打平为单文件）
css/index.css            # Linaria 构建期提取的静态样式
\`\`\`

在 \`package.json\` 中声明产物目录，使其随包发布：

\`\`\`json
{
    "files": ["esm", "cjs", "css", "declarations"]
}
\`\`\`

## 内置 Babel 配置

| 预设 / 插件 | 作用 |
|-------------|------|
| \`@babel/preset-env\` | 环境适配（\`targets: "defaults"\`） |
| \`@babel/preset-typescript\` | TypeScript 转译 |
| \`@babel/preset-react\` | React JSX（automatic runtime） |
| \`babel-plugin-react-compiler\` | React 19 Compiler（\`target: '19'\`） |

测试文件（\`__tests__/\`、\`*.test.*\`、\`*.spec.*\`）与 \`docs/\` 不参与构建。

## 设计令牌（generate:css-token）

在包根目录放置 \`token.toml\`：

\`\`\`toml
[build]
output = "./src/token.ts"                  # 生成目标
prefix = "button"                          # CSS 变量前缀 → --button-*
imports = ["@crab-dev/rc-token-semantic"]  # 上层令牌来源，供 $ref() 解析

[token]
opacity.disabled  = "0.4"
size.large.height = "40px"
size.large.gap    = "$ref(space.component-gap)"
\`\`\`

\`$ref(key)\` 会解析为上层令牌的 CSS 变量并带上兜底值：

\`\`\`
"$ref(space.component-gap)"
    → var(--token-semantic-space-component-gap, 8px)
\`\`\`

\`src/token.ts\` 是生成产物，**不要手动编辑**——改 \`token.toml\` 后重新执行 \`packify generate:css-token\`。

## API 文档（generate:docgen）

以 \`src/index.ts\` 追溯到默认导出的组件源文件，经 react-docgen 解析 Props，输出到 \`public/docgen.json\`。

若入口无法自动追溯（例如 \`index.ts\` 只做重导出），可在 \`package.json\` 中显式指定：

\`\`\`json
{
    "docgen": { "entry": "src/button.tsx" }
}
\`\`\`

## 测试（test）

Jest 尚未原生支持 ESM，\`packify test\` 会以 \`--experimental-vm-modules\` 启动一个 node 子进程来运行**调用方自己的** Jest —— 各包自行掌控 Jest 版本与配置，packify 只负责以正确的方式启动它，并透传命令行参数与退出码。

\`\`\`bash
packify test                          # 全量
packify test src/__tests__/x.test.tsx # 单文件
packify test -t "用例名"               # 按用例名过滤
\`\`\`
`,
    },
    {
        slug: "babel-plugin-auto-import-style",
        pkg: "@crab-dev/babel-plugin-auto-import-style",
        version: "0.0.3",
        title: "Auto Import Style 插件",
        role: "Babel",
        stage: "消费",
        summary: "编译期为消费方注入样式。import 组件即自动带上它与传递依赖的 CSS。",
        output: "消费方的样式 import",
        description: "用于处理组件样式自动导入, 属于 @crab-dev/crustify 的内部组件",
        readme: `<div align="center">
	<h1>@crab-dev/babel-plugin-auto-import-style</h1>
	<p>
		编译期为 <code>@crab-dev/rc-*</code> 组件自动注入样式导入，<br/>
		消费方只 import 组件，样式自动跟随，且传递依赖的样式按正确的级联顺序一并注入。
	</p>
</div>

## 它解决什么

零运行时的 Linaria 把样式提取成了独立的 \`css/index.css\`，代价是消费方每引入一个组件，就得手写一行样式导入——组件的传递依赖还得自己补齐，漏一行就少一截样式。

本插件把这件事挪到编译期：

\`\`\`tsx
// 你写的
import Dialog from '@crab-dev/rc-dialog';
\`\`\`

\`\`\`tsx
// 编译后（rc-dialog 内部复用了 rc-button）
import Dialog from '@crab-dev/rc-dialog';
import '/abs/path/to/rc-button/css/index.css';   // 依赖在前
import '/abs/path/to/rc-dialog/css/index.css';   // 本体在后
\`\`\`

## 安装

\`\`\`bash
yarn add -D @crab-dev/babel-plugin-auto-import-style
\`\`\`

通常无需单独安装：\`@crab-dev/crustify\` 已在其内置 Babel 配置中注册了本插件，用 crustify 开发即自动生效。

## 手动注册

\`\`\`js
// babel.config.js
export default {
    plugins: ["@crab-dev/babel-plugin-auto-import-style"],
};
\`\`\`

插件**没有任何选项**，注册即用。

## 行为

- **匹配范围** — 仅处理形如 \`@crab-dev/rc-*\` 的 import；\`import type\` 不触发注入。
- **传递依赖** — 沿被引入包的 \`dependencies\` 递归收集所有 \`@crab-dev/rc-*\` 依赖的 \`css/index.css\`。
- **级联顺序** — 依赖在前、本体在后，与 CSS 层叠语义一致：父组件的令牌得以覆盖子组件的默认值。
- **去重** — 同一份 CSS 在一个模块内只注入一次；文件里已手写的样式导入也会被识别，不重复注入。
- **注入绝对路径** — 注入的是解析后的绝对文件路径，而非 \`@crab-dev/rc-*/css/index.css\` 这样的包名路径。

> **为何是绝对路径：** Yarn PnP 的严格模式禁止一个包直接访问「孙依赖」的 bare specifier——即便该包在磁盘上确实存在。插件沿 manifest 链逐跳解析（每一跳都在各自包的 PnP 边界内完成），最终把绝对路径写进消费方源码，从而完全绕过消费端对包名的二次解析。

## 定位

内部工具，服务于 \`@crab-dev/*\` 组件库的样式分发，不面向通用场景。
`,
    },
];

export default toolboxManifest;
