[build]
output = "./src/token.ts"
prefix = "button"

[token]

transition = "transform 90ms ease-out, box-shadow 90ms ease-out, background-color 90ms ease-out"
opacity.loading = "0.65"

size.large.gap = "10px"
size.large.height = "40px"
size.large.padding = "0 15px"
size.large.border.radius = "10px"
size.large.font.size = "16px"

size.middle.gap = "8px"
size.middle.height = "32px"
size.middle.padding = "0 15px"
size.middle.border.radius = "8px"
size.middle.font.size = "14px"

size.small.gap = "6px"
size.small.height = "24px"
size.small.padding = "0 7px"
size.small.border.radius = "6px"
size.small.font.size = "14px"

primary.color = "oklch(1 0 0)"
primary.background.color = "oklch(0.2855 0.0113 271)"
primary.background.color-disabled = "rgba(0, 0, 0, 0.04)"
primary.background.color-hover = "oklch(0.2442 0.0077 274.63)"
primary.background.color-active = "oklch(0.2855 0.0113 271)"
primary.box-shadow = "oklch(0.6518 0.1916 251.64 / 10%) 0px 2px 0px 0px"

link.color = "oklch(0.3608 0.0113 271)"
link.color-hover = "oklch(0.3608 0.0113 271)"
link.color-active = "oklch(0.3608 0.0113 271)"
link.background.color = "transparent"
link.background.color-disabled = "transparent"
link.text.underline-offset = "-2px"
link.text.decoration.color = "red"
link.text.decoration.width = "2px"

text.background.color-hover = "rgba(0,0,0,0.04)"
text.background.color-active = "rgba(0,0,0,0.15)"

dashed.color = "oklch(0.2855 0.0113 271)"
dashed.color-hover = "oklch(0.2855 0.0113 271)"
dashed.color-active = "oklch(0.2855 0.0113 271)"
dashed.background.color = "oklch(1 0 0)"
dashed.background.color-disabled = "rgba(0, 0, 0, 0.04)"
dashed.box-shadow = "oklch(0 0 0 / 2%) 0px 2px 0px 0px"
dashed.border-width = "1px"
dashed.border-style = "dashed"
dashed.border-color = "oklch(0.2855 0.0113 271)"
dashed.border-color-hover = "oklch(0.2855 0.0113 271)"
dashed.border-color-active = "oklch(0.2855 0.0113 271)"

subtle.color = "oklch(0 0 0 / 88%)"
subtle.color-hover = "oklch(0 0 0 / 88%)"
subtle.color-active = "oklch(0 0 0 / 88%)"
subtle.background.color = "oklch(1 0 0)"
subtle.background.color-disabled = "rgba(0, 0, 0, 0.04)"
subtle.border-width = "1px"
subtle.border-style = "solid"
subtle.border-color = "oklch(0.8853 0 0)"
subtle.border-color-hover = "oklch(0.8853 0 0)"
subtle.border-color-active = "oklch(0.8853 0 0)"
subtle.box-shadow = "0 2px 0 oklch(0 0 0 / 2%)"