[package]
name = "crab-core"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { workspace = true }
actix-web = { workspace = true }
serde =  { workspace = true }
toml = { workspace = true }
log = { workspace =  true }
serde_json = { workspace = true }
anyhow = { workspace = true }
sea-orm = { workspace = true }
argon2 = { workspace = true }
jsonwebtoken = { workspace = true }
utoipa = { workspace = true }
env_logger = { workspace = true }
chrono = { workspace = true}
colored = { workspace = true }
