import { defineTokens } from "@crab-dev/css";
import palette from "@crab-dev/rc-token-global";
import type { ThemeColorContract } from "./types.js";

export const themeColorContract: ThemeColorContract = defineTokens({
    light: {
        control: { thumb: palette.white, track: palette.zinc["500"], trackHover: palette.zinc["600"] },
        brand: {
            primary: palette.purple["40"],
            hover: palette.purple["30"],
            active: palette.purple["20"],
            subtle: palette.purple["40"],
        },
        background: {
            surface: palette.white,
            elevated: palette.white,
            sunken: palette.zinc["50"],
            inverse: palette.zinc["950"],
            overlay: `color-mix(in oklch, ${palette.black} 45%, transparent)`,
            disabled: palette.zinc["100"],
            hoverSubtle: palette.zinc["100"],
            activeSubtle: palette.zinc["200"],
            selected: palette.purple["90"],
        },
        text: {
            primary: palette.zinc["950"],
            secondary: palette.zinc["700"],
            tertiary: palette.zinc["600"],
            onBrand: palette.white,
            inverse: palette.zinc["50"],
            disabled: palette.zinc["500"],
            link: palette.purple["40"],
            linkHover: palette.purple["30"],
        },
        border: {
            subtle: palette.zinc["200"],
            default: palette.zinc["600"],
            hover: palette.zinc["700"],
            strong: palette.zinc["700"],
            focus: palette.purple["40"],
            error: palette.red["600"],
        },
        focusRing: `var(--token-semantic-color-border-focus, ${palette.purple["40"]})`,
        selection: {
            background: palette.purple["90"],
            border: palette.purple["40"],
            foreground: palette.purple["10"],
        },
        highlight: {
            background: palette.amber["100"],
            backgroundActive: palette.amber["300"],
            foreground: palette.zinc["950"],
        },
        feedback: {
            error: {
                text: `var(--token-semantic-color-feedback-error, ${palette.red["800"]})`,
                icon: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                border: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                background: palette.red["50"],
                backgroundHover: palette.red["100"],
                solid: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                solidHover: palette.red["700"],
                solidActive: palette.red["800"],
                onSolid: palette.white,
            },
            success: {
                text: `var(--token-semantic-color-feedback-success, ${palette.green["800"]})`,
                icon: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                border: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                background: palette.green["50"],
                backgroundHover: palette.green["100"],
                solid: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                solidHover: palette.green["800"],
                solidActive: palette.green["900"],
                onSolid: palette.white,
            },
            warning: {
                text: `var(--token-semantic-color-feedback-warning, ${palette.amber["900"]})`,
                icon: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                border: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                background: palette.amber["50"],
                backgroundHover: palette.amber["100"],
                solid: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                solidHover: palette.amber["800"],
                solidActive: palette.amber["900"],
                onSolid: palette.white,
            },
            info: {
                text: `var(--token-semantic-color-feedback-info, ${palette.blue["800"]})`,
                icon: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                border: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                background: palette.blue["50"],
                backgroundHover: palette.blue["100"],
                solid: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                solidHover: palette.blue["700"],
                solidActive: palette.blue["800"],
                onSolid: palette.white,
            },
        },
        fill: {
            subtle: palette.zinc["100"],
            default: palette.zinc["300"],
            strong: palette.zinc["700"],
            translucent: `color-mix(in oklch, ${palette.black} 8%, transparent)`,
            inactive: palette.zinc["300"],
            active: palette.purple["40"],
        },
        focusShadow: `0 0 0 3px color-mix(in oklch, var(--token-semantic-color-focus-ring, var(--token-semantic-color-border-focus, ${palette.purple["40"]})) 20%, transparent)`,
    },
    dark: {
        control: { thumb: palette.zinc["50"], track: palette.zinc["700"], trackHover: palette.zinc["600"] },
        brand: {
            primary: palette.purple["80"],
            hover: `color-mix(in oklch, ${palette.purple["80"]} 50%, ${palette.purple["90"]})`,
            active: palette.purple["90"],
            subtle: palette.purple["80"],
        },
        background: {
            surface: palette.zinc["950"],
            elevated: palette.zinc["900"],
            sunken: palette.black,
            inverse: palette.white,
            overlay: `color-mix(in oklch, ${palette.black} 72%, transparent)`,
            disabled: palette.zinc["800"],
            hoverSubtle: palette.zinc["900"],
            activeSubtle: palette.zinc["800"],
            selected: palette.purple["30"],
        },
        text: {
            primary: palette.zinc["50"],
            secondary: palette.zinc["300"],
            tertiary: palette.zinc["400"],
            onBrand: palette.purple["20"],
            inverse: palette.zinc["950"],
            disabled: palette.zinc["500"],
            link: palette.purple["80"],
            linkHover: palette.purple["90"],
        },
        border: {
            subtle: palette.zinc["800"],
            default: palette.zinc["500"],
            hover: palette.zinc["400"],
            strong: palette.zinc["300"],
            focus: palette.purple["80"],
            error: palette.red["400"],
        },
        focusRing: `var(--token-semantic-color-border-focus, ${palette.purple["80"]})`,
        selection: {
            background: palette.purple["30"],
            border: palette.purple["80"],
            foreground: palette.purple["90"],
        },
        highlight: {
            background: palette.amber["950"],
            backgroundActive: palette.amber["800"],
            foreground: palette.zinc["50"],
        },
        feedback: {
            error: {
                text: `var(--token-semantic-color-feedback-error, ${palette.red["300"]})`,
                icon: `var(--token-semantic-color-feedback-error, ${palette.red["400"]})`,
                border: `var(--token-semantic-color-feedback-error, ${palette.red["400"]})`,
                background: `color-mix(in oklab, ${palette.red["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklab, ${palette.red["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-error, ${palette.red["600"]})`,
                solidHover: palette.red["700"],
                solidActive: palette.red["800"],
                onSolid: palette.white,
            },
            success: {
                text: `var(--token-semantic-color-feedback-success, ${palette.green["300"]})`,
                icon: `var(--token-semantic-color-feedback-success, ${palette.green["500"]})`,
                border: `var(--token-semantic-color-feedback-success, ${palette.green["500"]})`,
                background: `color-mix(in oklab, ${palette.green["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklab, ${palette.green["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                solidHover: palette.green["800"],
                solidActive: palette.green["900"],
                onSolid: palette.white,
            },
            warning: {
                text: `var(--token-semantic-color-feedback-warning, ${palette.amber["300"]})`,
                icon: `var(--token-semantic-color-feedback-warning, ${palette.amber["500"]})`,
                border: `var(--token-semantic-color-feedback-warning, ${palette.amber["500"]})`,
                background: `color-mix(in oklab, ${palette.amber["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklab, ${palette.amber["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                solidHover: palette.amber["800"],
                solidActive: palette.amber["900"],
                onSolid: palette.white,
            },
            info: {
                text: `var(--token-semantic-color-feedback-info, ${palette.blue["300"]})`,
                icon: `var(--token-semantic-color-feedback-info, ${palette.blue["500"]})`,
                border: `var(--token-semantic-color-feedback-info, ${palette.blue["500"]})`,
                background: `color-mix(in oklab, ${palette.blue["500"]} 18%, ${palette.zinc["950"]})`,
                backgroundHover: `color-mix(in oklab, ${palette.blue["500"]} 26%, ${palette.zinc["950"]})`,
                solid: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                solidHover: palette.blue["700"],
                solidActive: palette.blue["800"],
                onSolid: palette.white,
            },
        },
        fill: {
            subtle: palette.zinc["800"],
            default: palette.zinc["600"],
            strong: palette.zinc["300"],
            translucent: `color-mix(in oklch, ${palette.white} 12%, transparent)`,
            inactive: palette.zinc["700"],
            active: palette.purple["80"],
        },
        focusShadow: `0 0 0 3px color-mix(in oklch, var(--token-semantic-color-focus-ring, var(--token-semantic-color-border-focus, ${palette.purple["80"]})) 20%, transparent)`,
    },
});
