import { defineTokens } from "@crab-dev/css";
import palette from "@crab-dev/rc-token-global";
import type { ResolvedThemeColorContract } from "./types.js";

export const themeColorContract: ResolvedThemeColorContract = defineTokens({
    light: {
        surface: {
            canvas: `var(--token-semantic-color-background-sunken, ${palette.material["neutral"][98]})`,
            content: `var(--token-semantic-color-background-surface, ${palette.material["neutral"][98]})`,
            container: palette.material["neutral"][94],
            raised: `var(--token-semantic-color-background-elevated, ${palette.material["neutral"][96]})`,
            overlay: palette.material["neutral"][92],
            lowest: palette.material["neutral"][100],
            low: palette.material["neutral"][96],
            high: palette.material["neutral"][92],
            highest: palette.material["neutral"][90],
            dim: palette.material["neutral"][87],
            bright: palette.material["neutral"][98],
        },
        brandContainer: {
            background: `var(--token-semantic-color-selection-background, ${palette.purple["90"]})`,
            foreground: `var(--token-semantic-color-selection-foreground, ${palette.purple["10"]})`,
        },
        secondary: { primary: palette.material["secondary"][40], onPrimary: palette.material["secondary"][100], container: palette.material["secondary"][90], onContainer: palette.material["secondary"][10] },
        tertiary: { primary: palette.material["tertiary"][40], onPrimary: palette.material["tertiary"][100], container: palette.material["tertiary"][90], onContainer: palette.material["tertiary"][10] },
        control: { thumb: palette.white, track: palette.material["neutral-variant"][50], trackHover: palette.material["neutral-variant"][50] },
        brand: {
            primary: palette.purple["40"],
            hover: palette.purple["30"],
            active: palette.purple["20"],
            subtle: palette.purple["40"],
        },
        background: {
            surface: palette.material["neutral"][98],
            elevated: palette.material["neutral"][96],
            sunken: palette.material["neutral"][98],
            inverse: palette.material["neutral"][10],
            overlay: `color-mix(in oklch, ${palette.black} 32%, transparent)`,
            disabled: palette.material["neutral"][90],
            hoverSubtle: `color-mix(in oklch, ${palette.material["neutral"][10]} calc(var(--token-semantic-state-opacity-hover, ${palette.opacity[8]}) * 100%), ${palette.material["neutral"][98]})`,
            activeSubtle: `color-mix(in oklch, ${palette.material["neutral"][10]} calc(var(--token-semantic-state-opacity-pressed, ${palette.opacity[12]}) * 100%), ${palette.material["neutral"][98]})`,
            selected: palette.purple["90"],
        },
        text: {
            primary: palette.material["neutral"][10],
            secondary: palette.material["neutral-variant"][30],
            tertiary: palette.material["neutral-variant"][30],
            onBrand: palette.white,
            inverse: palette.material["neutral"][95],
            disabled: palette.material["neutral-variant"][50],
            link: palette.purple["40"],
            linkHover: palette.purple["30"],
        },
        border: {
            subtle: palette.material["neutral-variant"][80],
            default: palette.material["neutral-variant"][50],
            hover: palette.material["neutral-variant"][30],
            strong: palette.material["neutral-variant"][30],
            focus: palette.purple["40"],
            error: palette.material["error"][40],
        },
        focusRing: `var(--token-semantic-color-border-focus, ${palette.purple["40"]})`,
        selection: {
            background: palette.purple["90"],
            border: palette.purple["40"],
            foreground: palette.purple["10"],
        },
        highlight: {
            background: palette.amber["100"],
            backgroundActive: palette.amber["300"],
            foreground: palette.material["neutral"][10],
        },
        feedback: {
            error: {
                text: `var(--token-semantic-color-feedback-error, ${palette.material["error"][10]})`,
                icon: `var(--token-semantic-color-feedback-error, ${palette.material["error"][40]})`,
                border: `var(--token-semantic-color-feedback-error, ${palette.material["error"][40]})`,
                background: palette.material["error"][90],
                backgroundHover: palette.material["error"][90],
                solid: `var(--token-semantic-color-feedback-error, ${palette.material["error"][40]})`,
                solidHover: palette.material["error"][30],
                solidActive: palette.material["error"][20],
                onSolid: palette.material["error"][100],
            },
            success: {
                text: `var(--token-semantic-color-feedback-success, ${palette.green["800"]})`,
                icon: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                border: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                background: palette.green["50"],
                backgroundHover: palette.green["100"],
                solid: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                solidHover: palette.green["800"],
                solidActive: palette.green["900"],
                onSolid: palette.white,
            },
            warning: {
                text: `var(--token-semantic-color-feedback-warning, ${palette.amber["900"]})`,
                icon: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                border: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                background: palette.amber["50"],
                backgroundHover: palette.amber["100"],
                solid: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                solidHover: palette.amber["800"],
                solidActive: palette.amber["900"],
                onSolid: palette.white,
            },
            info: {
                text: `var(--token-semantic-color-feedback-info, ${palette.blue["800"]})`,
                icon: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                border: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                background: palette.blue["50"],
                backgroundHover: palette.blue["100"],
                solid: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                solidHover: palette.blue["700"],
                solidActive: palette.blue["800"],
                onSolid: palette.white,
            },
        },
        fill: {
            subtle: palette.material["neutral"][90],
            default: palette.material["neutral-variant"][80],
            strong: palette.material["neutral-variant"][30],
            translucent: `color-mix(in oklch, ${palette.black} 8%, transparent)`,
            inactive: palette.material["neutral-variant"][80],
            active: palette.purple["40"],
        },
        focusShadow: `0 0 0 3px color-mix(in oklch, var(--token-semantic-color-focus-ring, var(--token-semantic-color-border-focus, ${palette.purple["40"]})) 20%, transparent)`,
    },
    dark: {
        surface: {
            canvas: `var(--token-semantic-color-background-sunken, ${palette.material["neutral"][6]})`,
            content: `var(--token-semantic-color-background-surface, ${palette.material["neutral"][6]})`,
            container: palette.material["neutral"][12],
            raised: `var(--token-semantic-color-background-elevated, ${palette.material["neutral"][10]})`,
            overlay: palette.material["neutral"][17],
            lowest: palette.material["neutral"][4],
            low: palette.material["neutral"][10],
            high: palette.material["neutral"][17],
            highest: palette.material["neutral"][22],
            dim: palette.material["neutral"][6],
            bright: palette.material["neutral"][24],
        },
        brandContainer: {
            background: `var(--token-semantic-color-selection-background, ${palette.purple["30"]})`,
            foreground: `var(--token-semantic-color-selection-foreground, ${palette.purple["90"]})`,
        },
        secondary: { primary: palette.material["secondary"][80], onPrimary: palette.material["secondary"][20], container: palette.material["secondary"][30], onContainer: palette.material["secondary"][90] },
        tertiary: { primary: palette.material["tertiary"][80], onPrimary: palette.material["tertiary"][20], container: palette.material["tertiary"][30], onContainer: palette.material["tertiary"][90] },
        control: { thumb: palette.material["neutral"][90], track: palette.material["neutral-variant"][30], trackHover: palette.material["neutral-variant"][50] },
        brand: {
            primary: palette.purple["80"],
            hover: `color-mix(in oklch, ${palette.purple["80"]} 50%, ${palette.purple["90"]})`,
            active: palette.purple["90"],
            subtle: palette.purple["80"],
        },
        background: {
            surface: palette.material["neutral"][6],
            elevated: palette.material["neutral"][10],
            sunken: palette.material["neutral"][6],
            inverse: palette.material["neutral"][90],
            overlay: `color-mix(in oklch, ${palette.black} 32%, transparent)`,
            disabled: palette.material["neutral-variant"][30],
            hoverSubtle: `color-mix(in oklch, ${palette.material["neutral"][90]} calc(var(--token-semantic-state-opacity-hover, ${palette.opacity[8]}) * 100%), ${palette.material["neutral"][6]})`,
            activeSubtle: `color-mix(in oklch, ${palette.material["neutral"][90]} calc(var(--token-semantic-state-opacity-pressed, ${palette.opacity[12]}) * 100%), ${palette.material["neutral"][6]})`,
            selected: palette.purple["30"],
        },
        text: {
            primary: palette.material["neutral"][90],
            secondary: palette.material["neutral-variant"][80],
            tertiary: palette.material["neutral-variant"][80],
            onBrand: palette.purple["20"],
            inverse: palette.material["neutral"][20],
            disabled: palette.material["neutral-variant"][60],
            link: palette.purple["80"],
            linkHover: palette.purple["90"],
        },
        border: {
            subtle: palette.material["neutral-variant"][30],
            default: palette.material["neutral-variant"][60],
            hover: palette.material["neutral-variant"][80],
            strong: palette.material["neutral-variant"][80],
            focus: palette.purple["80"],
            error: palette.material["error"][80],
        },
        focusRing: `var(--token-semantic-color-border-focus, ${palette.purple["80"]})`,
        selection: {
            background: palette.purple["30"],
            border: palette.purple["80"],
            foreground: palette.purple["90"],
        },
        highlight: {
            background: palette.amber["950"],
            backgroundActive: palette.amber["800"],
            foreground: palette.material["neutral"][90],
        },
        feedback: {
            error: {
                text: `var(--token-semantic-color-feedback-error, ${palette.material["error"][90]})`,
                icon: `var(--token-semantic-color-feedback-error, ${palette.material["error"][80]})`,
                border: `var(--token-semantic-color-feedback-error, ${palette.material["error"][80]})`,
                background: palette.material["error"][30],
                backgroundHover: palette.material["error"][30],
                solid: `var(--token-semantic-color-feedback-error, ${palette.material["error"][80]})`,
                solidHover: palette.material["error"][90],
                solidActive: palette.material["error"][100],
                onSolid: palette.material["error"][20],
            },
            success: {
                text: `var(--token-semantic-color-feedback-success, ${palette.green["300"]})`,
                icon: `var(--token-semantic-color-feedback-success, ${palette.green["500"]})`,
                border: `var(--token-semantic-color-feedback-success, ${palette.green["500"]})`,
                background: `color-mix(in oklab, ${palette.green["500"]} 18%, ${palette.material["neutral"][6]})`,
                backgroundHover: `color-mix(in oklab, ${palette.green["500"]} 26%, ${palette.material["neutral"][6]})`,
                solid: `var(--token-semantic-color-feedback-success, ${palette.green["700"]})`,
                solidHover: palette.green["800"],
                solidActive: palette.green["900"],
                onSolid: palette.white,
            },
            warning: {
                text: `var(--token-semantic-color-feedback-warning, ${palette.amber["300"]})`,
                icon: `var(--token-semantic-color-feedback-warning, ${palette.amber["500"]})`,
                border: `var(--token-semantic-color-feedback-warning, ${palette.amber["500"]})`,
                background: `color-mix(in oklab, ${palette.amber["500"]} 18%, ${palette.material["neutral"][6]})`,
                backgroundHover: `color-mix(in oklab, ${palette.amber["500"]} 26%, ${palette.material["neutral"][6]})`,
                solid: `var(--token-semantic-color-feedback-warning, ${palette.amber["700"]})`,
                solidHover: palette.amber["800"],
                solidActive: palette.amber["900"],
                onSolid: palette.white,
            },
            info: {
                text: `var(--token-semantic-color-feedback-info, ${palette.blue["300"]})`,
                icon: `var(--token-semantic-color-feedback-info, ${palette.blue["500"]})`,
                border: `var(--token-semantic-color-feedback-info, ${palette.blue["500"]})`,
                background: `color-mix(in oklab, ${palette.blue["500"]} 18%, ${palette.material["neutral"][6]})`,
                backgroundHover: `color-mix(in oklab, ${palette.blue["500"]} 26%, ${palette.material["neutral"][6]})`,
                solid: `var(--token-semantic-color-feedback-info, ${palette.blue["600"]})`,
                solidHover: palette.blue["700"],
                solidActive: palette.blue["800"],
                onSolid: palette.white,
            },
        },
        fill: {
            subtle: palette.material["neutral-variant"][30],
            default: palette.material["neutral-variant"][50],
            strong: palette.material["neutral-variant"][80],
            translucent: `color-mix(in oklch, ${palette.white} 12%, transparent)`,
            inactive: palette.material["neutral-variant"][30],
            active: palette.purple["80"],
        },
        focusShadow: `0 0 0 3px color-mix(in oklch, var(--token-semantic-color-focus-ring, var(--token-semantic-color-border-focus, ${palette.purple["80"]})) 20%, transparent)`,
    },
});
