[package]
name = "crab-infinitum"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crab-core",
    "crab-core-entity",
    "crab-mod-auth-jwt"
]

[workspace.dependencies]
actix-web = "4.9.0"
anyhow = "1.0.95"
derive_more = { version = "2.0.1", features = ["full"] }
serde =  { version = "1.0.215", features = ["derive"] }
chrono = "0.4.38"
serde_json = "1.0.133"
toml = "0.8.20"
log = "0.4.22"
sea-orm = { version = "1.1.5", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros"] }
argon2 = "0.5.3"
env_logger = "0.11.6"
jsonwebtoken = "9.3.1"
crab-core = { path = "./crab-core" }
crab-core-entity = { path = "./crab-core-entity"}
utoipa = { version = "5.3.1", features = ["actix_extras"]}
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"]}
utoipa-actix-web = "0.1.2"
colored = "3.0.0"

[dependencies]
actix-web = "4.9.0"
sea-orm = { version = "1.1.5", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros"] }
toml = "0.8.20"
log = "0.4.22"
anyhow = "1.0.95"
derive_more = { version = "2.0.1", features = ["full"] }
serde =  { version = "1.0.215", features = ["derive"] }
chrono = "0.4.38"
serde_json = "1.0.133"
crab-core = { path = "./crab-core" }
crab-mod-auth-jwt = { path = "./crab-mod-auth-jwt"}
env_logger = "0.11.6"
utoipa = { version = "5.3.1", features = ["actix_extras"]}
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"]}
utoipa-actix-web = "0.1.2"


