[package]
name = "crab-infinitum"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "crab-core",
    "crab-core-entity",
    "crab-core-websocket",
    "crab-core-auth-jwt",
    "crab-core-basic",
]

[workspace.dependencies]
actix-web = "4.10.2"
actix-web-actors = "4.3.1"
colored = "3.0.0"
actix-ws = "0.3.0"
anyhow = "1.0.97"
derive_more = { version = "2.0.1", features = ["full"] }
serde =  { version = "1.0.219", features = ["derive"] }
chrono = "0.4.40"
serde_json = "1.0.140"
toml = "0.8.20"
log = "0.4.26"
sea-orm = { version = "1.1.7", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros"] }
argon2 = "0.5.3"
env_logger = "0.11.7"
jsonwebtoken = "9.3.1"
crab-core = { path = "./crab-core" }
crab-core-entity = { path = "./crab-core-entity"}
crab-core-auth-jwt = { path = "./crab-core-auth-jwt"}
utoipa = { version = "5.3.1", features = ["actix_extras"]}
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"]}
utoipa-actix-web = "0.1.2"
futures-util = "0.3.31"
actix = "0.13.5"

[dependencies]
actix-web = "4.9.0"
sea-orm = { version = "1.1.5", features = [ "sqlx-postgres", "runtime-actix-rustls", "macros"] }
toml = "0.8.20"
log = "0.4.22"
anyhow = "1.0.95"
derive_more = { version = "2.0.1", features = ["full"] }
serde =  { version = "1.0.215", features = ["derive"] }
chrono = "0.4.38"
serde_json = "1.0.133"
crab-core = { path = "./crab-core" }
crab-core-auth-jwt = { path = "./crab-core-auth-jwt"}
crab-core-websocket = { path = "./crab-core-websocket"}
crab-core-entity = { path = "./crab-core-entity"}
crab-core-basic = { path = "./crab-core-basic"}
env_logger = "0.11.6"
utoipa = { version = "5.3.1", features = ["actix_extras"]}
utoipa-swagger-ui = { version = "9.0.0", features = ["actix-web"]}
utoipa-actix-web = "0.1.2"
actix-web-actors = "4.3.1"
argon2 = "0.5.3"


