# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest Test CI

on:
  push:
    branches: [ "canary" ]
  pull_request:
    branches: [ "canary" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Test Crustify ${{ matrix.node-version }}
      uses: actions/setup-node@v4
    - name: Enable Corepack
      run: corepack enable 
    - name: Set Yarn version to 4.x
      run: yarn set version stable
    - name: Install dependencies
      run: node -v  && yarn install
    - name: Build the project
      run: yarn build
    - name: Run Jest Test
      run: NODE_OPTIONS="--experimental-vm-modules"  yarn test
