# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "canary" ]
  pull_request:
    branches: [ "canary" ]

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        lfs: true
    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: '24'
    - name: Enable Corepack
      run: corepack enable
    - name: Install project package manager
      run: corepack install
    - name: Install dependencies
      run: yarn install --immutable
    - name: Generate design tokens
      run: yarn generate:token
    - name: Run ESLint
      run: yarn lint
    - name: Run typecheck
      run: yarn typecheck
    - name: Build the project
      run: yarn build:library
    - name: Run Wake Test
      run: yarn test
    - name: Build Wake Docs
      run: yarn docs:build
